#@data/values
---
tap:
  ingress_domain: tap.example.com
  cnrs_subdomain: tap.example.com
container_registry:
  hostname: harbor.example.com
  username: admin
  password:
  repository: tap-wkld
workshop_git:
  username: user
  branch: main